# Copyright 2022 Hewlett Packard Enterprise Development LP

name: "Docker Build & Publish"
on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  container-build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Build & Publish App
      uses: hpe-actions/docker-build@v2
      with:
        dockerfile: ./Dockerfile
        repository_path: /
