# Copyright 2023 Hewlett Packard Enterprise Development LP

name: Secrets API
on: [push]
jobs:
  get_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for existing secrets
        run: |
          curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ANDY_TEST_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/hpe-cds/actions/secrets/ANDY_TEST_SECRET
