# Copyright 2022 Hewlett Packard Enterprise Development LP

name: Pipeline Test Run
on: [push]
jobs:
  pre_build_tests:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/hpe-cds/sc-containers-images/cds-go-dev:0.0.68-0-ga3d26f8
      options: --user root
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run lint
        run: make lint
      - name: Run kubescore
        run: make kubescore
#      - name: Generate tag
#        run: |
#          git config user.name cds-github-ci
#          git config user.email cds-github-ci@hpe.com
#          tag-manage create --min 0.1.0 --push -vv
#          echo "::set-output name=TAG_VERSION::$(tag-manage describe --default 0.0.0)"

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy fs scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  helm-push:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/hpe-cds/sc-containers-images/cds-go-dev:0.0.68-0-ga3d26f8
      options: --user root
    permissions:
      id-token: write # This is required for requesting the JWT
      actions: read
      contents: read
      packages: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Helm build
      run: "helm package helm/hello-world --version 0.1 --app-version 0.1"
    - name: Push to helm
      uses: hpe-cds/helm-push@dev
      with:
        skip_checkout: false
        helm_package: hello-world-0.1.tgz

