# Copyright 2022 Hewlett Packard Enterprise Development LP

name: Pipeline Test Run
on: [push]
jobs:
  helm-push:
    name: Push to helm
    uses: hpe-cds/helm-push/.github/workflows/helm-process.yml@dev
    with:
      helm_package: helm/hello-world
      version: 0.2
